# Generated by Django 5.2.1 on 2025-05-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_soft_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
