# Generated by Django 5.0.4 on 2024-04-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='custom_field',
            new_name='custom',
        ),
    ]
