# Generated by Django 5.2.1 on 2025-05-28 05:53

import accounts_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_customuser_is_soft_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts_app.models.CustomUserManager()),
            ],
        ),
    ]
