# Generated by Django 5.0.4 on 2024-04-17 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='videos/')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='videoflix.video')),
            ],
        ),
    ]
