# Generated by Django 5.0.4 on 2024-04-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0002_videoversion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoVersion',
        ),
    ]
