# Generated by Django 5.0.4 on 2024-06-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_avatar'),
        ('videoflix', '0003_video_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_videos', to='users.profile'),
        ),
    ]
