# Generated by Django 5.0.4 on 2024-06-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0004_alter_video_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('Movie', 'Movie'), ('TV-Show', 'TV-Show')], default='Movie', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Documentary', 'Documentary'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Sports', 'Sports')], default='Action', max_length=100),
        ),
    ]
