# Generated by Django 5.0.4 on 2024-04-17 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0004_remove_video_video_file_video_original_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='original_file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_1080p',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_480p',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_720p',
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.CreateModel(
            name='VideoResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='videos/converted')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='converted', to='videoflix.video')),
            ],
        ),
    ]
