# Generated by Django 5.0.4 on 2024-04-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0005_remove_video_original_file_remove_video_video_1080p_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoresolution',
            name='file',
            field=models.FileField(upload_to='videos'),
        ),
    ]
