# Generated by Django 5.0.4 on 2024-04-17 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0006_alter_videoresolution_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoresolution',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='videoflix.video'),
        ),
    ]
