# Generated by Django 5.0.4 on 2024-04-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0007_alter_videoresolution_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='videoresolution',
            name='file',
            field=models.FileField(max_length=500, upload_to='videos'),
        ),
    ]
