# Generated by Django 5.0.4 on 2024-04-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0009_rename_video_file_video_video_filepath_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_filepath',
            new_name='video_file',
        ),
        migrations.RenameField(
            model_name='videoresolution',
            old_name='converted_filepath',
            new_name='converted_file',
        ),
    ]
