services:
  postgres:
    image: postgres
    container_name: videoflix-dev-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: videoflix_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ElsuE348Df45gf
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: videoflix-dev-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass foobared

  rqworker:
    build:
      context: ..
      dockerfile: dockerlocal/Dockerfile.worker
    container_name: videoflix-dev-rq-worker
    working_dir: /app
    volumes:
      - ..:/app
    command: >
      sh -c "
        export DJANGO_SETTINGS_MODULE=core.settings &&
        python manage.py rqworker default
      "
    environment:
      - DATABASE_URL=postgresql://postgres:ElsuE348Df45gf@postgres:5432/videoflix_db
      - REDIS_HOST=redis
    depends_on:
      - redis
      - postgres


volumes:
  postgres_data:
