FROM python:3.12-slim

# Installiere ffmpeg und alle Dependencies
RUN apt-get update && \
    apt-get install -y ffmpeg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ../requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Das eigentliche Kommando gibt weiter docker-compose.yaml vor
