# Generated by Django 5.0.4 on 2024-04-19 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
