# Generated by Django 5.0.4 on 2024-04-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('avatars/avatar_0.png', 'Avatar 0'), ('avatars/avatar_1.png', 'Avatar 1'), ('avatars/avatar_2.png', 'Avatar 2'), ('avatars/avatar_3.png', 'Avatar 3'), ('avatars/avatar_4.png', 'Avatar 4'), ('avatars/avatar_5.png', 'Avatar 5'), ('avatars/avatar_6.png', 'Avatar 6')], max_length=255),
        ),
    ]
