# Generated by Django 5.2.1 on 2025-07-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_rename_thumbnail_video_thumbnail_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='uploaded_at',
            new_name='created_at',
        ),
    ]
