# Generated by Django 5.0.4 on 2024-06-06 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0002_video_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
