# Generated by Django 5.2.1 on 2025-07-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_rename_uploaded_at_video_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('Movie', 'Movie'), ('TV-Show', 'TV-Show'), ('Action', 'Action')], default='Movie', max_length=100),
        ),
    ]
