# Generated by Django 5.2.1 on 2025-07-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_alter_video_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='genre',
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Documentary', 'Documentary'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Sports', 'Sports'), ('Action', 'Action')], default='Action', max_length=100),
        ),
    ]
