# Generated by Django 5.2.1 on 2025-07-23 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0005_remove_video_genre_alter_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Documentary', 'Documentary'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Sports', 'Sports')], default='Action', max_length=100),
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='video_app.video'),
        ),
    ]
